// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieythtcmdspgjusgtuey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlleXRodGNtZHNwZ2p1c2d0dWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTk1OTIsImV4cCI6MjA4ODU3NTU5Mn0.g6edQBwkKsbSjnFQ7zP2kK8HQytKBv9gfnQTHSBewro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});